[package]
name = "example"
version = "0.1.0"
authors = ["Frank Andrew Stevenson"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dp-3t-client = { path = "../" }